# In-Class Assignment 1

## Shane Waldron

### 1.

In [30]:
import pandas as pd
import numpy as np
import sweetviz as sv
from sklearn.model_selection import train_test_split, GridSearchCV, cross_val_score
from sklearn.preprocessing import MinMaxScaler
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import mean_squared_error, r2_score
from sklearn.linear_model import LinearRegression

# Loading the data
df = pd.read_csv("insurance.csv")
df.head()

   age     sex     bmi  children smoker     region      charges
0   19  female  27.900         0    yes  southwest  16884.92400
1   18    male  33.770         1     no  southeast   1725.55230
2   28    male  33.000         3     no  southeast   4449.46200
3   33    male  22.705         0     no  northwest  21984.47061
4   32    male  28.880         0     no  northwest   3866.85520

### 2.

In [31]:
# Visualizing the data with SweetViz
report = sv.analyze(df, target_feat='charges')
report.show_html()

                                             |          | [  0%]   00:00 -> (? left)

Report SWEETVIZ_REPORT.html was generated! NOTEBOOK/COLAB USERS: the web browser MAY not pop up, regardless, the report IS saved in your notebook/colab files.

### Exploratory Data Analysis

First, looking at the shape and properties of the dataset. We have 1338 observations and 7 columns, which include age, sex, bmi, children, smoker, region, and charges. We have no missing values across the dataset. 

Next, looking at the distributions of the columns, we see the charges are pretty significantly skewed to the right, which makes sense as higher insurance charges are more rare. We also see that as age and bmi increase, insurance charges increase. Also, we see that males have higher insurance charges than females, on average.

In [32]:
# Encode categoricals
df_encoded = pd.get_dummies(df, drop_first=True).astype(int)

In [33]:
X = df_encoded.drop(columns=['charges'], axis=1)
y = df_encoded['charges']

In [34]:
X_train, X_test, y_train, y_test = train_test_split(X,y, test_size=0.2, random_state=42)

In [35]:
scaler = MinMaxScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.fit_transform(X_test)

In [36]:
# Baseline Linear Regression Model
lr = LinearRegression()
lr.fit(X_train_scaled, y_train)
y_pred_lr = lr.predict(X_test_scaled)
mse_lr = mean_squared_error(y_test, y_pred_lr)
r2_lr = r2_score(y_test, y_pred_lr)
print("MSE:", mse_lr,"R2:", r2_lr)

MSE: 33592199.36026507 R2: 0.7836229196787973

In [37]:
# Baseline Random Forest Model
rf = RandomForestRegressor(random_state=42)
rf.fit(X_train, y_train)
y_pred_rf = rf.predict(X_test)
mse_rf = mean_squared_error(y_test, y_pred_rf)
r2_rf = r2_score(y_test, y_pred_rf)
print("MSE:", mse_rf,"R2:", r2_rf)

MSE: 22179121.673664946 R2: 0.8571378569063584

In [38]:
# CV with baseline models with r2 as scoring metric
cv_scores_lr = cross_val_score(lr, X_train_scaled, y_train, cv = 5, scoring='r2')
cv_scores_rf = cross_val_score(lr, X_train, y_train, cv = 5, scoring='r2')

print(cv_scores_lr.mean())
print(cv_scores_rf.mean())

0.7330691648735671
0.7330691648735673

The random forest model outperforms the linear regression model, achieving a higher R2 (0.857 vs 0.784) and lower MSE (22.2M vs 33.6M) on the test set.

In [39]:
param_grid = {
    'n_estimators': [100,200],
    'max_depth': [None, 10, 20],
    'min_samples_split': [2, 5, 10, 20],
    'max_features': [1.0, 0.7, 0.5, 0.3]
}

rf_grid = GridSearchCV(rf, param_grid, cv=5, scoring='r2')
rf_grid.fit(X_train, y_train)

GridSearchCV(cv=5, estimator=RandomForestRegressor(random_state=42),
             param_grid={'max_depth': [None, 10, 20],
                         'max_features': [1.0, 0.7, 0.5, 0.3],
                         'min_samples_split': [2, 5, 10, 20],
                         'n_estimators': [100, 200]},
             scoring='r2')

In [40]:
# Looking at the top 20 models based on rank from the GridSearchCV Results
results = pd.DataFrame(rf_grid.cv_results_)
top20 = results.sort_values("rank_test_score").head(20)

top20[[
    "rank_test_score",
    "mean_test_score",
    "param_n_estimators",
    "param_max_depth",
    "param_min_samples_split",
    "param_max_features"
]]

,rank_test_score,mean_test_score,param_n_estimators,param_max_depth,param_min_samples_split,param_max_features
14,1,0.846503,100,None,20,0.7
78,1,0.846503,100,20,20,0.7
15,3,0.846459,200,None,20,0.7
79,3,0.846459,200,20,20,0.7
47,5,0.846224,200,10,20,0.7
46,6,0.846115,100,10,20,0.7
53,7,0.844892,200,10,10,0.5
52,8,0.844696,100,10,10,0.5
45,9,0.844676,200,10,10,0.7
44,10,0.844636,100,10,10,0.7
85,11,0.843807,200,20,10,0.5
21,11,0.843807,200,None,10,0.5
84,13,0.843624,100,20,10,0.5
20,13,0.843624,100,None,10,0.5
13,15,0.843482,200,None,10,0.7
77,15,0.843482,200,20,10,0.7
12,17,0.843441,100,None,10,0.7
76,17,0.843441,100,20,10,0.7
71,19,0.842702,200,20,20,1.0
7,19,0.842702,200,None,20,1.0

There are 2 models that are tied for top performance, with the same parameters of 100 estimators, minimum observations to split of 20, and max features of 0.7. The only difference is the max depth, which for one of the forests is none and for the other is 20. Given that there is no performance benefit to increased complexity in the tree, the model I would choose is the one with max depth of 20 as it's simpler.

In [41]:
# Fitting the RF model with my chosen parameters

rf = RandomForestRegressor(
    n_estimators=100,
    max_depth=20,
    min_samples_split=20,
    max_features=0.7,
    random_state=42
)

rf.fit(X_train, y_train)

RandomForestRegressor(max_depth=20, max_features=0.7, min_samples_split=20,
                      random_state=42)

In [42]:
# Comparing test and train performance
y_train_pred = rf.predict(X_train)
y_test_pred = rf.predict(X_test)

train_score = r2_score(y_train, y_train_pred)
test_score = r2_score(y_test, y_test_pred)

print("Train R2:", train_score)
print("Test R2:", test_score)

Train R2: 0.8959457893950922
Test R2: 0.8694086599236517

The R squared values for the test and train are similar enough to where I don't think there I don't think I can conclude that there is overfitting happening.